# Generated by Django 4.1.10 on 2023-09-23 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesupload',
            name='uploadedby',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='filesupload',
            name='uploadedon',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
