# Generated by Django 4.1.10 on 2023-09-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_filesupload_uploadedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesupload',
            name='uploadedby',
        ),
    ]
